service: aws-serverless-authentication
frameworkVersion: '4'

plugins:
  - serverless-esbuild

package:
  individually: true

provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  deploymentMethod: direct
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Resource: !GetAtt AuthUserPool.Arn
          Action:
            - cognito-idp:AdminGetUser
  environment:
    COGNITO_CLIENT_ID: !Ref AuthUserPoolClient
    COGNITO_POOL_ID: !Ref AuthUserPool
  httpApi:
    authorizers:
      CognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt AuthUserPool.ProviderURL
        audience:
          - !Ref AuthUserPoolClient

build:
  esbuild: false

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: node20
    exclude:
      - '@aws-sdk/*'
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10

resources:
  Resources:
    AuthUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        DeletionProtection: INACTIVE
        UserPoolName: AuthUserPool
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false
            TemporaryPasswordValidityDays: 2
        Schema:
          - Name: given_name
            Mutable: true
            Required: true
            AttributeDataType: String
    AuthUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: AuthUserPoolClient
        UserPoolId: !Ref AuthUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        TokenValidityUnits:
          AccessToken: hours
          RefreshToken: hours
        AccessTokenValidity: 3
        RefreshTokenValidity: 72 # 3 days
functions:
  cognitoCustomMessage:
    handler: src/functions/cognitoCustomMessage.handler
    events:
      - cognitoUserPool:
          pool: AuthUserPool
          trigger: CustomMessage
          existing: true
          forceDeploy: true
  signUp:
    handler: src/functions/signUp.handler
    events:
      - httpApi:
          method: POST
          path: /auth/sign-up
  accountConfirmation:
    handler: src/functions/accountConfirmation.handler
    events:
      - httpApi:
          method: POST
          path: /auth/account-confirmation
  signIn:
    handler: src/functions/signIn.handler
    events:
      - httpApi:
          method: POST
          path: /auth/sign-in
  refreshToken:
    handler: src/functions/refreshToken.handler
    events:
      - httpApi:
          method: POST
          path: /auth/refresh-token
  forgotPassword:
    handler: src/functions/forgotPassword.handler
    events:
      - httpApi:
          method: POST
          path: /auth/forgot-password
  resetPassword:
    handler: src/functions/resetPassword.handler
    events:
      - httpApi:
          method: POST
          path: /auth/reset-password
  profile:
    handler: src/functions/profile.handler
    events:
      - httpApi:
          method: GET
          path: /user/profile
          authorizer:
            name: CognitoAuthorizer
